### ISSUE TITLE
Problem at "Generate delta mu and delta w plots for the computed alignments"

### ISSUE THREAD

**Issue by dsb66** [thomsonlab/popalign#9]
I am running your tutorial using my own data. I can go through all the steps, but I run into an error at the step "Generate delta mu and delta w plots for the computed alignments":

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-41-65b6089cccc5> in <module>
     26 '''
     27 pop['controlstring']="CT"
---> 28 PA.plot_deltas(pop, figsize=(10,10), sortby='mu', pthresh = 0.05)

/usr/local/bin/miniconda3/lib/python3.8/site-packages/popalign/popalign.py in plot_deltas(pop, figsize, sortby, pthresh, showplot)
   3557 
   3558                 else:
-> 3559                         pvals_ws = np.ones(len(mean_ws))
   3560                         pvals_mus = np.ones(len(mean_mus))
   3561                         pvals_covs = np.ones(len(mean_covs))

NameError: name 'mean_ws' is not defined
------------------------------------------------------------------------------

I checked teh code and I could not find the line where 'mean_ws' is defined.

**Comment by sisichen-dev** [comment]
Great, thanks. I think that’s a bug. I changed the variable name to
mean_delta_ws. Check to see if this works for you now.

One question, do you have multiple replicates of a control sample? If so
you can set the ‘control string’ to a common string within the sample
names. For example, if your control samples are called ‘wildtype1’,
‘wildtype2’, … , you can set the control string to ‘wildtype’ by executing:
pop[‘controlstring’]=‘wildtype'

This will allow you to generate FDR-corrected p-values in computing these
delta values.

Sisi

On October 26, 2020 at 11:10:13 PM, dsb66 (notifications@github.com) wrote:

I am running your tutorial using my own data. I can go through all the
steps, but I run into an error at the step "Generate delta mu and delta w
plots for the computed alignments":
------------------------------

NameError Traceback (most recent call last)
in
26 '''
27 pop['controlstring']="CT"
---> 28 PA.plot_deltas(pop, figsize=(10,10), sortby='mu', pthresh = 0.05)

/usr/local/bin/miniconda3/lib/python3.8/site-packages/popalign/popalign.py
in plot_deltas(pop, figsize, sortby, pthresh, showplot)
3557
3558 else:
-> 3559 pvals_ws = np.ones(len(mean_ws))
3560 pvals_mus = np.ones(len(mean_mus))
3561 pvals_covs = np.ones(len(mean_covs))
NameError: name 'mean_ws' is not defined

I checked teh code and I could not find the line where 'mean_ws' is defined.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/thomsonlab/popalign/issues/9>, or unsubscribe

**Comment by dsb66** [comment]
Thanks, the change fixes the problem.
I only have a control sample. I am testing against a sample with a gene knockout which changes the cell population mix. I want to see if your method is better at detecting these changes.
